# This workflow uses actions that are not certified by GitHub.
# They are provided by a third-party and are governed by
# separate terms of service, privacy policy, and support
# documentation.

# This workflow helps you trigger a SonarQube analysis of your code and populates
# GitHub Code Scanning alerts with the vulnerabilities found.
# (this feature is available starting from SonarQube 9.7, Developer Edition and above)

# 1. Make sure you add a valid GitHub configuration to your SonarQube (Administration > DevOps platforms > GitHub)

# 2. Import your project on SonarQube
#     * Add your repository as a new project by clicking "Create project" from your homepage.
#
# 3. Select GitHub Actions as your CI and follow the tutorial
#     * a. Generate a new token and add it to your GitHub repository's secrets using the name SONAR_TOKEN
#          (On SonarQube, click on your avatar on top-right > My account > Security or ask your administrator)
#
#     * b. Copy/paste your SonarQube host URL to your GitHub repository's secrets using the name SONAR_HOST_URL
#
#     * c. Copy/paste the project Key into the args parameter below
#          (You'll find this information in SonarQube by following the tutorial or by clicking on Project Information at the top-right of your project's homepage)

# Feel free to take a look at our documentation (https://docs.sonarqube.org/latest/analysis/github-integration/)
# or reach out to our community forum if you need some help (https://community.sonarsource.com/c/sq/10)

name: SonarQube analysis

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]
  workflow_dispatch:

permissions:
    contents: read
    pull-requests: read # allows SonarQube to decorate PRs with analysis results

jobs:
  sonarqube:
    runs-on: ubuntu-latest
    #services:
     # qubesonar:
     #   image: sonarqube:latest
     #   options: --name qubesonar-container
     #   ports:
     #     - 9000:9000
    steps:
      #- name: Get SonarQube Container Name
      #  id: get_container_name
      #  run: |
      #    CONTAINER_NAME=$(echo ${{ services.qubesonar.name }})
      #    echo "SonarQube Container Name: $CONTAINER_NAME"
      #    echo "::set-output name=container_name::$CONTAINER_NAME"

     # - name: Get Container IP
     #   id: get_container_ip
     #   run: |
     #     CONTAINER_IP=$(docker inspect -f '{{range .NetworkSettings.Networks}}{{.IPAddress}}{{end}}' qubesonar-container)
     #     echo "Container IP: $CONTAINER_IP"
     #     echo "::set-output name=container_ip::$CONTAINER_IP"

      #- name: Run SonarQube Analysis
      #  run: |
       #   CONTAINER_IP=${{ steps.get_container_ip.outputs.container_ip }}
       #   SONAR_URL="http://${CONTAINER_IP}:9000"  # Assuming SonarQube runs on port 9000
       #   sonar-scanner -Dsonar.host.url=$SONAR_URL

      - uses: sonarsource/sonarqube-scan-action@master
        env:
          SONAR_HOST_URL: http://localhost:9000/

